<!DOCTYPE html>
<html>
<head>
	<title>Work Order</title>
	<style type="text/css">
		html{
    		font-family: Arial, Helvetica, sans-serif;
    	}
    	table{
    		border-collapse: collapse;
    	}
    	.content-1, .content-2, .content-3, .content-4{
    		font-size: 13px;
    	}
    	.page-break {
		    page-break-after: always;
		}
		.judul2{
			margin-top: 0px;
		}
		.text-center{
			text-align: center;
		}
		.text-right{
			text-align: right;
		}
		.text-left{
			text-align: left;
		}
		.underline{
			text-decoration: underline;
		}
		.bordered{
			border: 1px solid #000;
		}
		.body-content, .title-content{
			margin-top: -10px;
		}
		.box-machine-name{
			width: 100%;
			border: 1px solid #000;
			font-size: 13px;
			margin-top: 5px;
			padding: 3px;
			background-color: #e0e0e3;
		}
		.responsive-table{
			font-size: 8px;
		}
		.machine-info{
			margin-left: 20px;
			margin-top: 5px;
		}
		.content{
			width: 100%;
			margin-top: 15px;
			font-size: 0;
		}
		.work-info{
			padding-left: 90px;
			padding-right: 90px;
		}
		.data{
			font-size: 13px;
			display: inline-block;
			position: relative;
			border: 1px solid #000;
			text-align: center;
			width: 20px;
		}
	</style>
</head>
<body>
<div class="header">
	<div class="judul1 text-center">
		<h2>PINEHILL ARABIA FOOD LTD</h2>
		<p style="margin-top: -20px;">TECHINC JNF</p>
	</div>
	<div class="judul2 text-center">
		<p>
			Work Order
		</p>
	</div>
</div>
<div class="body">
	<div class="body-header">
		<p style="text-align: right; font-size: 12px;">{{ 'from ' . $start_date->format('d-M-Y') . ' to ' . $end_date->format('d-M-Y') }}</p>
		<table style="border: none; width: 100%; margin-bottom: 5px;">
			<tr>
				<td style="font-size: 12px; border: none; text-align: left;">Responsible person :</td>
				<td style="font-size: 12px; border: none; text-align: left; padding-left: 300px;">Approximate duration : @if(!empty($shutdown_num && $shutdown_per)) {{ $approximate_h . ' h ' . $approximate_m . ' m' }} @endif</td>
			</tr>
			<tr>
				<td style="font-size: 12px; border: none; text-align: left;">Generated by : {{ auth()->user()->name }}</td>
				<td style="font-size: 12px; border: none; text-align: left; padding-left: 300px;">Date and time of receipt of the OW :</td>
			</tr>
			<tr>
				<td style="font-size: 12px; border: none; text-align: left;">Reviewed by :</td>
				<td style="font-size: 12px; border: none; text-align: left; padding-left: 300px;">Date and time of return of the WO :</td>
			</tr>
			<tr>
				<td style="font-size: 12px; border: none; text-align: left;">Authorized by :</td>
			</tr>
		</table>
	</div><hr>
	<div class="body-content">
		<div class="box-machine-name">
			{{ $worklists->machine_name . ' ' . $worklists->capacity . ' ' . $worklists->brand . ' ' . $worklists->production_year }}
		</div>
		<div class="machine-info">
			<table class="responsive-table">
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Location:</td>
					<td style="text-align: left; border: none; font-size: 11px; color: #000;">\ JEDDAH NOODLE FACTORY\ {{ $worklists->lane_name }}\ {{ $area }}</td>
				</tr>
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Parent equipment:</td>
				</tr>
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Priority:</td>
					<td style="text-align: left; border: none; font-size: 11px; color: #000;">{{ $priority_1 }}</td>
				</tr>
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Classification 1:</td>
				</tr>
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Classification 2:</td>
				</tr>
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Cost center:</td>
					<td style="text-align: left; border: none; font-size: 11px; color: #000;">{{ $cost }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ $worklists->lane_name . ' ' . $worklists->machine_name }}</td>
				</tr>
			</table>
		</div>
		<div class="routine-title text-center underline" style="font-style: italic; font-size: 13px;">
			<p>Routine activities</p>
		</div>
		<div class="routine-pointcheck">
			<p style="font-size: 11px; margin-left: 55px;">
				Checkin moving mechanical system
			</p>
		</div>
		<div class="routine-info">
			<table class="responsive-table" style="margin-left: 70px; margin-top: 10px;">
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Frequency:</td>
					<td style="text-align: left; border: none; font-size: 11px; color: #000;">{{ $worklists->time . ' ' . $worklists->period . '(s)' }}</td>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82; padding-left: 200px;">Priority:</td>
					<td style="text-align: left; border: none; font-size: 11px; color: #000;">{{ $priority_2 }}</td>
				</tr>
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Approximate duration:</td>
					<td style="text-align: left; border: none; font-size: 11px; color: #000;">@if(!empty($approximate_h && $approximate_m)) {{ $approximate_h . ' h ' . $approximate_m . ' m'}} @endif</td>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82; padding-left: 200px;">Classification 1:</td>
				</tr>
				<tr>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82;">Requires shutdown:</td>
					<td style="text-align: left; border: none; font-size: 11px; color: #000;">@if(!empty($shutdown_num && $shutdown_per)) {{ $shutdown_num . ' ' . $shutdown_per . '(s)' }} @endif</td>
					<td style="text-align: right; border: none; font-size: 11px; color: #767c82; padding-left: 200px;">Classification 2:</td>
				</tr>
			</table>
		</div>
		<div class="work-info">
			<div class="content">@foreach($periods as $date)<div class="data">@if($date->format('Y-m-d') == $worklists->date_check)<b style="@if($worklists->status_check == 'open') color: #696ffb; @elseif($worklists->status_check == 'waiting') color:#FF6F59; @elseif($worklists->status_check == 'close') color: #4CCEAC; @endif">{{ $date->format('d') }}</b>@else{{ $date->format('d') }}@endif</div>@endforeach</div>
		</div>
	</div>
</div>
<div class="page-break"></div>
<div class="header">
	<div class="judul1 text-center">
		<h2>PINEHILL ARABIA FOOD LTD</h2>
		<p style="margin-top: -20px;">TECHINC JNF</p>
	</div>
	<div class="judul2 text-center">
		<p>
			Work Order
		</p>
	</div>
</div>
<div class="body">
	<hr>
	<div class="body-content">
		<div class="content-1">
			<div class="title_content">
				<p>Spare parts and consumables</p>
			</div>
			<div class="body-content text-center bordered" style="padding-left: 10px; padding-right: 10px;">
				Do not write spare parts and consumables, as their consumption is recorded automatically when generating the output movement from the Warehouse.
			</div>
		</div>
		<div class="content-2">
			<div class="title-content">
				<p>Other</p>
			</div>
			<div class="body-content bordered">
				<table style="width: 100%; padding-bottom: 10px;" class="text-left">
					<tr style="font-size: 10px;">
						<td style="padding-left: 7px;">Description</td>
						<td>Part number</td>
						<td>Quantity</td>
						<td style="padding-right: 7px;">Unit</td>
					</tr>
					@for($i=0; $i<16; $i++)
					<tr>
						<td style="padding-left: 7px;">___________________________________________________</td>
						<td>___________________</td>
						<td>________</td>
						<td style="padding-right: 7px;">_______</td>
					</tr>
					@endfor
				</table>
			</div>
		</div>
		<div class="content-3">
			<div class="title-content">
				<p>Labor hand</p>
			</div>
			<div class="body-content">
				<table style="width: 100%; font-size: 10px; border-collapse: collapse;" class="text-left" border="1">
					<tr>
						@for($z=0; $z<4; $z++)
						<td style="padding-bottom: 20px;">Name</td>
						@endfor
					</tr>
					<tr >
						@for($a=0; $a<4; $a++)
						<td>
							<table style="width: 100%; padding-bottom: 4px;">
								<tr>
									<td style="padding-left: 7px;">Date</td>
									<td>Time</td>
								</tr>
								@for($b=0; $b<7; $b++)
								<tr>
									<td style="padding-left: 7px;">______________</td>
									<td>____________</td>
								</tr>
								@endfor
							</table>
						</td>
						@endfor
					</tr>
				</table>
			</div>
		</div>
		<div class="content-4">
			<div class="title-content">
				<p>External services</p>
			</div>
			<div class="body-content bordered">
				<table style="width: 100%; padding-bottom: 5px;" class="text-left">
					<tr style="font-size: 10px;">
						<td style="padding-left: 7px;">Company name</td>
						<td>Service</td>
						<td>Date</td>
						<td>Quantity</td>
					</tr>
					@for($i=0; $i<5; $i++)
					<tr>
						<td style="padding-left: 7px;">_________________________________________</td>
						<td>__________________________</td>
						<td>__________</td>
						<td>________</td>
					</tr>
					@endfor
				</table>
			</div>
		</div>
		<div class="end-content text-center" style="font-size: 13px;">
			<br><br><p>______ of ______</p>
		</div>
	</div>
</div>
</body>
</html>